name = "vpnstan-cloudflare"
main = "src/index.js"
compatibility_date = "2026-10-02"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/api/*", "/sub/*", "/ws"]

[[d1_databases]]
binding = "DB"
database_name = "vpnstan_panel_db"
database_id = "db0d6d70-2cb9-4334-9942-00c265efd801"

[vars]
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin"
PANEL_NAME = "vpnstan"
